export * from './banks.ts'
export * from './plan.ts'
export * from './speech.ts'
export * from './text.ts'
export * from './voice.ts'
export * from '@animalese/core'
export { analyze, detectLanguage, enLetters, frontends, syllabify } from '@animalese/g2p'
export type { AnalyzeOptions, Frontend } from '@animalese/g2p'
export * from '@animalese/web'
