/**
 * Builds the Mandarin syllable inventory and picks a carrier character for each syllable.
 *
 * Candidates come from GB2312, whose first level holds the 3755 most common characters.
 * We prefer characters with a single reading (a TTS engine may read 镐 as gǎo instead of hào),
 * then level 1 over level 2, then first tone, then fourth, second, third and neutral,
 * because a flat or falling tone gives the cleanest recording to retune later.
 */
import { writeFileSync } from 'node:fs'

import { pinyin, polyphonic } from 'pinyin-pro'

/**
 * Hand-picked carriers where every single-reading candidate is obscure (恧, 仂) but a
 * common polyphone is almost always read the way we want in isolation.
 */
const overrides: Record<string, string> = {
  chuai: '揣',
  fou: '否',
  le: '勒',
  ne: '呢',
  nv: '女',
}

const decoder = new TextDecoder('gbk')
const toneRank = [4, 0, 2, 3, 1, 4]
const best = new Map<string, { char: string, score: number }>()

for (let high = 0xB0; high <= 0xF7; high++) {
  for (let low = 0xA1; low <= 0xFE; low++) {
    const char = decoder.decode(new Uint8Array([high, low]))
    if (char.length !== 1 || char === '�')
      continue
    const numbered = pinyin(char, { toneType: 'num', v: true })
    const syllable = numbered.replace(/\d/g, '')
    // Unassigned code points (D7FA–D7FE) decode to private-use characters with no reading.
    if (!/^[a-z]+$/.test(syllable))
      continue
    const tone = Number(numbered.match(/\d/)?.[0] ?? 0)
    const readings = polyphonic(char, { toneType: 'none' })[0]!.split(' ').length
    const score = (readings > 1 ? 100 : 0) + (high <= 0xD7 ? 0 : 10) + toneRank[tone]!
    const current = best.get(syllable)
    if (!current || score < current.score)
      best.set(syllable, { char, score })
  }
}

const entries = [...best].sort(([a], [b]) => a.localeCompare(b))
const body = entries.map(([syllable, { char: candidate }]) => [syllable, overrides[syllable] ?? candidate] as const).map(([syllable, char]) => `  ${/^[a-z]+$/.test(syllable) ? syllable : `'${syllable}'`}: '${char}',`).join('\n')
writeFileSync(
  new URL('../src/zh/syllables.ts', import.meta.url),
  `// Generated by scripts/generate-zh-syllables.ts. Do not edit.\n\n/** Toneless pinyin syllable (ü written as v) to a common carrier character. */\nexport const syllables: Record<string, string> = {\n${body}\n}\n`,
)
console.info(`${entries.length} syllables`)
